stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - ssh-add <(echo "$MASTER_PRIVATE_KEY")
    
deploy:
  stage: deploy
  only:
    - master
  script:
    - ssh root@142.93.11.143 'cd main && git pull origin master && cat docker-compose.yml && ./restart'
