version: '3'

services:
  frontend:
    image: moneygames/frontend:master
    ports:
      - "9000:9000"
  serverlist:
    image: moneygames/serverlist:spectating
    ports:
      - "6001:6001"
  playerstatus:
    image: moneygames/playerstatus:master
    ports:
      - "6002:6002"
  matchmaker:
    depends_on:
      - redis-gameservers
    image: moneygames/matchmaker:master
    environment:
      - MM_TIMER_SECONDS=5
      - MM_MIN_PLAYERS=2
      - SSL=false
    ports:
      - "8000:8000"
  gameserver-service:
    image: moneygames/gameserver-service:master
    environment:
      - GSTAG=master
    depends_on:
      - redis-gameservers
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [ node.role == manager ]
  payserver:
    image: moneygames/payserver:master
    environment:
      - NET=testnet
      - BCOIN=testnet.moneygames.io
      - APIKEY=hunterkey
      - SSL=false
    depends_on:
      - redis-players
      - redis-gameservers
    ports:
      - "7000:7000"
  receipt:
    image: moneygames/receipt:master
    environment:
      - NET=testnet
      - BCOIN=testnet.moneygames.io
      - APIKEY=hunterkey
      - SSL=false
    depends_on:
      - redis-players
      - redis-gameservers
    ports:
      - "7002:7002"
  redis-players:
    image: redis
    ports:
      - "9001:6379"
  redis-gameservers:
    image: redis
    ports:
      - "9002:6379"
  vis:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [ node.role == manager ]
