version: '3'

services:
  frontend:
    build: frontend
    ports:
      - "9000:9000"
  matchmaker:
    build: matchmaker
    ports:
      - "8000:8000"
  gs1:
    build: gameserver
    ports:
      - "9001:10000"
      
  gs2:
    build: gameserver
    ports:
      - "9002:10000"
  gs3:
    build: gameserver
    ports:
      - "9003:10000"
