version: '3'

services:
  frontend:
    image: moneygames/frontend:master
    ports:
      - "9000:9000"
  matchmaker:
    depends_on:
      - redis-gameservers
    image: moneygames/matchmaker:master
    ports:
      - "8000:8000"
  gameserver-service:
    image: moneygames/gameserver-service:master
    depends_on:
      - redis-gameservers
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [ node.role == manager ]
  payserver:
    image: moneygames/payserver:master
    depends_on:
      - redis-players
    ports:
      - "7000:7000"
  redis-players:
    image: redis
  redis-gameservers:
    image: redis
  vis:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [ node.role == manager ]
