version: '3'

services:
  frontend:
    build: frontend
    ports:
      - "9000:9000"
  matchmaker:
    build: matchmaker
    ports:
      - "8000:8000"
  gameserver-service:
    build: gameserver-service
    restart: always
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
