version: '3'

services:
  frontend:
    image: parthmehrotra/frontend
    build: frontend
    ports:
      - "9000:9000"
  matchmaker:
    depends_on:
      - redis
    image: parthmehrotra/matchmaker
    build: matchmaker
    ports:
      - "8000:8000"
  gameserver-service:
    image: parthmehrotra/gameserver-service
    build: gameserver-service
    depends_on:
      - redis
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [ node.role == manager ]
  redis:
    image: redis
    ports:
      - "6379:6379"
  vis:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [ node.role == manager ]
