version: '3'

services:
  frontend:
    image: moneygames/frontend:bow-calculate-pot
    ports:
      - "9000:9000"
  serverlist:
    image: moneygames/serverlist:master
    ports:
      - "6001:6001"
  playerstatus:
    image: moneygames/playerstatus:master
    ports:
      - "6002:6002"
  matchmaker:
    depends_on:
      - redis-gameservers
    image: moneygames/matchmaker:bow-calculate-pot
    ports:
      - "8000:8000"
  gameserver-service:
    image: moneygames/gameserver-service:master
    environment:
      - GSTAG=bow-calculate-pot
    depends_on:
      - redis-gameservers
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [ node.role == manager ]
  payserver:
    image: moneygames/payserver:bow-send-payments
    depends_on:
      - redis-players
      - redis-gameservers
    ports:
      - "7000:7000"
  redis-players:
    image: redis
    ports:
      - "9001:6379"
  redis-gameservers:
    image: redis
    ports:
      - "9002:6379"
  vis:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [ node.role == manager ]
